version: '3.8'

services:
  client:
    image: client:latest
    container_name: client
    hostname: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    restart: always
    networks:
      - webnet

networks:
  webnet: